// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;


#[derive(serde::Serialize, serde::Deserialize, Clone, Queryable, Insertable, Identifiable)]
pub struct Card {
    pub id: String,
    pub list_id: String,
    pub title: String,
    pub body: String,
    pub created_at: String,
    pub updated_at: String,
}

